languageCode = "en-us"
theme = "portio"
baseURL = "https://xuani-yoga.tk/"
paginate = 6
title = "HYGGE"

[params]
blogPageURL = "blog"
contactLink = "contact"
icon = "images/icon.png"
formspreeURL = "https://formspree.io/f/mgerzrbo"
googleAnalytics = "G-HRRB3RXD09"

[params.address]

[params.map]
APIkey = "YOUR GOOGLE MAP API"