languageCode = "en-us"
theme = "portio"
baseURL = "https://xuani-yoga.tk/"
formspreeURL = "https://formspree.io/f/mgerzrbo"
googleAnalytics = "G-HRRB3RXD09"
paginate = 6
title = "HYGGE"
icon = "images/favicon.png"

[params]
blogPageURL = "blog"
contactLink = "contact"
icon = "images/favicon.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"

[params.address]

[params.map]
APIkey = "YOUR GOOGLE MAP API"