languageCode = "en-us"
theme = "portio"
baseURL = "https://xuanyoga.tk/"
paginate = 6
title = "XUAN YOGA & LIFESTYLE"

[params]
blogPageURL = "blog"
contactLink = "contact"
icon = "https://xuanyoga.tk/images/hygge-icon.png"
formspreeURL = "https://formspree.io/f/mgerzrbo"
googleAnalytics = "G-HRRB3RXD09"

[params.address]

[params.map]
APIkey = "YOUR GOOGLE MAP API"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.asciidocExt]
verbose = false
trace = false
sectionNumbers = false
noHeaderOrFooter = true
safeMode = "unsafe"
extensions = []
backend = "html5"
failureLevel = "fatal"
workingFolderCurrent = false
preserveTOC = false

[markup.asciidocExt.attributes]

[markup.blackFriday]
footnoteReturnLinkContents = ""
nofollowLinks = false
footnoteAnchorPrefix = ""
angledQuotes = false
smartDashes = true
skipHTML = false
smartypants = true
taskLists = true
fractions = true
latexDashes = true
smartypantsQuotesNBSP = false
hrefTargetBlank = false
plainIDAnchors = true
noreferrerLinks = false

[markup.goldmark]

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = "github"

[markup.goldmark.parser.attribute]
block = false
title = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = true

[markup.highlight]
hl_Lines = ""
noClasses = true
anchorLineNos = false
lineAnchors = ""
lineNoStart = 1
codeFences = true
style = "monokai"
tabWidth = 4
lineNumbersInTable = true
guessSyntax = false
lineNos = false

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2