# Official Docs: https://www.netlifycms.org/docs/configuration-options/
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# site_url: https://tiiyuu.github.io/test/
display_url: https://tiiyuu.github.io/test/
# logo_url: https://your-site.com/images/logo.svg # for CMS UI logo
publish_mode: editorial_workflow
show_preview_links: false
media_folder: static/images
public_folder: images
collections:
  - name: 'blog_post'
    label: 'Blog Post'
    folder: 'content/blog'
    description: 'Create a new post right now!'
    create: true
    extension: 'md'
    slug: '{{year}}_{{month}}_{{day}}_{{hour}}_{{minute}}_{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Feature Image', name: 'featureImage', widget: 'image' }
      - { label: 'Post Image', name: 'postImage', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'portfolio_post'
    label: 'Portfolio Post'
    folder: 'content/portfolio'
    description: '妮妮♥尼尼'
    create: true
    extension: 'md'
    slug: '{{year}}_{{month}}_{{day}}_{{hour}}_{{minute}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'thumbnail', name: 'thumbnail', widget: 'image' }
      - { label: 'body', name: 'body', widget: 'markdown' }
  - name: 'layouts'
    label: 'Layouts'
    files:
      - file: 'data/navBar.yml'
        label: 'Navigation Bar'
        name: 'navbar'
        fields:
          - { label: 'logo', name: 'logo', widget: 'image' }
          - { label: 'menu', name: 'menu', widget: 'list', allow_add: false, fields: [
              { label: 'name', name: 'name', widget: 'string' }] }
      - file: 'data/hero.yml'
        label: 'Hero'
        name: 'hero'
        fields:
          - { label: 'Enable', name: 'enable', widget: 'boolean' }
          - { label: 'background color', name: 'bgColor', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'bubble color', name: 'bubbleColor', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'Left Image', name: 'leftImage', widget: 'image' }
          - { label: 'Right Image', name: 'rightImage', widget: 'image' }
          - { label: 'top Title', name: 'topTitle', widget: 'text' }
          - { label: 'content', name: 'content', widget: 'markdown' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'VideoThumb', name: 'videoThumb', widget: 'image' }
          - { label: 'VideoURL', name: 'videoURL', widget: 'text' }
      - file: 'data/aboutSection.yml'
        label: 'About'
        name: 'about'
        fields:
          - { label: 'Enable', name: 'enable', widget: 'boolean' }
          - { label: 'back Image', name: 'backImage', widget: 'image' }
          - { label: 'bubble color', name: 'bubbleColor', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'box color', name: 'boxColor', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'top Title', name: 'topTitle', widget: 'text' }
          - { label: 'title', name: 'title', widget: 'markdown' }
          - { label: 'Content', name: 'content', widget: 'markdown' }
          - { label: 'Image', name: 'image', widget: 'image' }
      - file: 'data/serviceSection.yml'
        label: 'Service'
        name: 'service'
        fields:
          - { label: 'enable', name: 'enable', widget: 'boolean' }
          - { label: 'top Title', name: 'topTitle', widget: 'text' }
          - { label: 'title', name: 'title', widget: 'markdown' }
          - { label: 'services', name: 'services', widget: 'list', allow_add: true, add_to_top: true, fields: [
              { label: 'content', name: 'content', widget: 'markdown' },
              { label: 'image', name: 'image', widget: 'image' }] }
      - file: 'data/portfolioSection.yml'
        label: 'Work'
        name: 'work'
        fields:
          - { label: 'enable', name: 'enable', widget: 'boolean' }
          - { label: 'top Title', name: 'topTitle', widget: 'text' }
          - { label: 'title', name: 'title', widget: 'markdown' }
      - file: 'data/resumeSection.yml'
        label: 'Resume'
        name: 'resume'
        fields:
          - { label: 'enable', name: 'enable', widget: 'boolean' }
          - { label: 'background color', name: 'bgColor', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'top Title', name: 'topTitle', widget: 'text' }
          - { label: 'title', name: 'title', widget: 'markdown' }
          - { label: 'tab1Name', name: 'tab1Name', widget: 'text' }
          - { label: 'tab2Name', name: 'tab2Name', widget: 'text' }
          - { label: 'education', name: 'education', widget: 'list', allow_add: true, add_to_top: true, fields: [
              { label: 'content', name: 'content', widget: 'markdown' },
              { label: 'time', name: 'time', widget: 'text' }] }
          - { label: 'experience', name: 'experience', widget: 'list', allow_add: true, add_to_top: true, fields: [
              { label: 'content', name: 'content', widget: 'markdown' },
              { label: 'time', name: 'time', widget: 'text' }] }
      - file: 'data/skillSection.yml'
        label: 'Skill'
        name: 'skill_section'
        fields:
          - { label: 'enable', name: 'enable', widget: 'boolean' }
          - { label: 'bubble color', name: 'bubbleColor', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'Left Image', name: 'leftImage', widget: 'image' }
          - { label: 'Right Image', name: 'rightImage', widget: 'image' }
          - { label: 'top Title', name: 'topTitle', widget: 'text' }
          - { label: 'content', name: 'content', widget: 'markdown' }
          - { label: 'image', name: 'image', widget: 'image' }
          - { label: 'skill', name: 'skill', widget: 'list', allow_add: true, add_to_top: true, fields: [
              { label: 'title', name: 'title', widget: 'text' },
              { label: 'percent', name: 'percent', widget: 'number', min: 0, max: 100 }] }
      - file: 'data/testimonialSection.yml'
        label: 'Testimonial'
        name: 'testimonial'
        fields:
          - { label: 'enable', name: 'enable', widget: 'boolean' }
          - { label: 'background color', name: 'bgColor', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'top Title', name: 'topTitle', widget: 'text' }
          - { label: 'title', name: 'title', widget: 'markdown' }
          - { label: 'testimonial', name: 'testimonial', widget: 'list', allow_add: true, add_to_top: true, fields: [
              {label: 'name', name: 'name', widget: 'string'},
              { label: 'comment', name: 'comment', widget: 'text' },
              { label: 'Date', name: 'time', widget: 'datetime', format: 'MMM DD, YYYY' },
              { label: 'star', name: 'star', widget: 'number', min: 0, max: 5 }] }
      - file: 'data/blogSection.yml'
        label: 'Blog'
        name: 'blog'
        fields:
          - { label: 'enable', name: 'enable', widget: 'boolean' }
          - { label: 'spin image', name: 'spinImage', widget: 'image' }
          - { label: 'top Title', name: 'topTitle', widget: 'string' }
          - { label: 'title', name: 'title', widget: 'markdown' }
          - { label: 'button Text', name: 'buttonText', widget: 'string' }
      - file: 'data/footer.yml'
        label: 'Footer'
        name: 'footer'
        fields:
          - { label: 'enable card', name: 'enable1', widget: 'boolean' }
          - { label: 'card background color', name: 'cardBgColor', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'shape1 color', name: 'shape1_Color', widget: 'color', enableAlpha: false, allowInput: true }
          - { label: 'shape1 opacity', name: 'shape1_Opacity', widget: 'number', value_type: 'float', min: 0.00, max: 1.00, step: 0.1 }
          - { label: 'shape2 color', name: 'shape2_Color', widget: 'color', enableAlpha: false, allowInput: true }
          - { label: 'shape2 opacity', name: 'shape2_Opacity', widget: 'number', value_type: 'float', min: 0.00, max: 1.00, step: 0.1 }
          - { label: 'top Title', name: 'topTitle', widget: 'string' }
          - { label: 'content', name: 'content', widget: 'string' }
          - { label: 'button Text', name: 'btnText', widget: 'string' }
          - { label: 'enable info', name: 'enable2', widget: 'boolean' }
          - { label: 'background color', name: 'bgColor', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'logo', name: 'footerLogo', widget: 'image' }
          - { label: 'title1', name: 'title1', widget: 'string' }
          - { label: 'content1', name: 'content1', widget: 'list', allow_add: true, add_to_top: true, fields: [
              {label: 'text', name: 'text', widget: 'string'},
              { label: 'url', name: 'url', widget: 'string' }] }
          - { label: 'title2', name: 'title2', widget: 'string' }
          - { label: 'content2', name: 'content2', widget: 'list', hint: 'Icon: https://fontawesome.com/v4.7/icons/', allow_add: true, add_to_top: true, fields: [
              {label: 'icon', name: 'icon', widget: 'string'},
              { label: 'text', name: 'text', widget: 'string' }] }
          - { label: 'copyright', name: 'copyright', widget: 'text' }
          - { label: 'social', name: 'social', widget: 'list', hint: 'Icon: https://fontawesome.com/v4.7/icons/', allow_add: true, add_to_top: true, fields: [
              {label: 'icon', name: 'icon', widget: 'string'},
              { label: 'url', name: 'url', widget: 'string' }] }
      - file: 'data/contact.yml'
        label: 'FAQ'
        name: 'contact'
        fields:
          - { label: 'enable', name: 'enable', widget: 'boolean' }
          - { label: 'bubble color', name: 'bubbleColor', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'Left Image', name: 'leftImage', widget: 'image' }
          - { label: 'Right Image', name: 'rightImage', widget: 'image' }
          - { label: 'title', name: 'title', widget: 'string' }
          - { label: 'breadcrumb', name: 'breadcrumb', widget: 'string' }
          - { label: 'faq', name: 'faq', widget: 'list', allow_add: true, add_to_top: true, fields: [
              { label: 'question', name: 'question', widget: 'string' },
              { label: 'answer', name: 'answer', widget: 'text'},
              { label: 'img', name: 'img', widget: 'image'},
              { label: 'fill Color', name: 'fillColor', widget: 'color', enableAlpha: true, allowInput: true }] }
          - { label: 'contact form', name: 'contact_form', widget: 'string'}
          - { label: 'name', name: 'name', widget: 'string'}
          - { label: 'email', name: 'email', widget: 'string'}
          - { label: 'message', name: 'message', widget: 'string'}
          - { label: 'agreement', name: 'agree', widget: 'string'}
          - { label: 'btn Text', name: 'btnText', widget: 'string'}
          - { label: 'btn Text Color', name: 'btnTextColor', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'btn Background Color', name: 'btnBgColor', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'btn Border Color', name: 'btnBorderColor', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'image', name: 'img', widget: 'image'}
  - name: 'Configuration'
    label: 'config'
    files:
      - file: 'config.toml'
        label: 'Configuration'
        name: 'configs'
        fields:
          - { label: 'Website title', name: 'title', widget: 'text' }
          - { label: 'favicon', name: 'icon', widget: 'image'}
          - { label: 'Formspree URL', name: 'formspreeURL', widget: 'text'}
          - { label: 'Google Analytics', name: 'googleAnalytics', widget: 'text'}