# Official Docs: https://www.netlifycms.org/docs/configuration-options/
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# site_url: https://tiiyuu.github.io/test/
display_url: https://tiiyuu.github.io/test/
# logo_url: https://your-site.com/images/logo.svg # for CMS UI logo
publish_mode: editorial_workflow
show_preview_links: false
media_folder: static/images
public_folder: images
collections:
  - name: 'blog_post'
    label: 'Blog Post'
    folder: 'content/blog'
    description: 'Create a new post right now!'
    create: true
    extension: 'md'
    slug: '{{year}}_{{month}}_{{day}}_{{hour}}_{{minute}}_{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Feature Image', name: 'featureImage', widget: 'image' }
      - { label: 'Post Image', name: 'postImage', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'portfolio'
    label: 'Portfolio'
    folder: 'content/portfolio'
    description: '妮妮♥尼尼'
    create: true
    extension: 'md'
    slug: '{{year}}_{{month}}_{{day}}_{{hour}}_{{minute}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'thumbnail', name: 'thumbnail', widget: 'image' }
      - { label: 'service', name: 'service', widget: 'string' }
      - { label: 'client', name: 'client', widget: 'string' }
      - { label: 'shortDescription', name: 'shortDescription', widget: 'text' }
      - { label: 'challenge', name: 'challenge', widget: 'text' }
      - { label: 'solution', name: 'solution', widget: 'text' }
      - { label: 'body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'data/hero.yml'
        label: 'Hero'
        name: 'hero'
        fields:
          - { label: 'Enable', name: 'enable', widget: 'boolean' }
          - { label: 'topTitle', name: 'topTitle', widget: 'text' }
          - { label: 'content', name: 'content', widget: 'markdown' }
          - { label: 'ButtonName', name: 'buttonName', widget: 'string' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'VideoThumb', name: 'videoThumb', widget: 'image', required: false }
          - { label: 'VideoURL', name: 'videoURL', widget: 'text', required: false }
      - file: 'data/aboutSection.yml'
        label: 'About'
        name: 'about'
        fields:
          - { label: 'Enable', name: 'enable', widget: 'boolean' }
          - { label: 'topTitle', name: 'topTitle', widget: 'text' }
          - { label: 'title', name: 'title', widget: 'markdown' }
          - { label: 'Content', name: 'content', widget: 'markdown' }
          - { label: 'Button1Name', name: 'button1Name', widget: 'string' }
          - { label: 'Button2Name', name: 'button2Name', widget: 'string' }
          - { label: 'Image', name: 'image', widget: 'image' }
      - file: 'data/serviceSection.yml'
        label: 'Service'
        name: 'service'
        fields:
          - { label: 'enable', name: 'enable', widget: 'boolean' }
          - { label: 'topTitle', name: 'topTitle', widget: 'text' }
          - { label: 'title', name: 'title', widget: 'markdown' }
          - { label: 'service', name: 'service', widget: 'list', allow_add: true, add_to_top: true, fields: [
              { label: 'content', name: 'content', widget: 'text' },
              { label: 'image', name: 'image', widget: 'image' }] }
      - file: 'data/portfolioSection.yml'
        label: 'Work'
        name: 'work'
        fields:
          - { label: 'enable', name: 'enable', widget: 'boolean' }
          - { label: 'topTitle', name: 'topTitle', widget: 'text' }
          - { label: 'title', name: 'title', widget: 'markdown' }
      - file: 'data/resumeSection.yml'
        label: 'Resume'
        name: 'resume'
        fields:
          - { label: 'enable', name: 'enable', widget: 'boolean' }
          - { label: 'topTitle', name: 'topTitle', widget: 'text' }
          - { label: 'title', name: 'title', widget: 'markdown' }
          - { label: 'tab1Name', name: 'tab1Name', widget: 'text' }
          - { label: 'tab2Name', name: 'tab2Name', widget: 'text' }
          - { label: 'education', name: 'education', widget: 'list', allow_add: true, add_to_top: true, fields: [
              { label: 'content', name: 'content', widget: 'markdown' },
              { label: 'time', name: 'time', widget: 'text' }] }
          - { label: 'experience', name: 'experience', widget: 'list', allow_add: true, add_to_top: true, fields: [
              { label: 'content', name: 'content', widget: 'markdown' },
              { label: 'time', name: 'time', widget: 'text' }] }
      - file: 'data/skillSection.yml'
        label: 'Skill'
        name: 'skill_section'
        fields:
          - { label: 'enable', name: 'enable', widget: 'boolean' }
          - { label: 'topTitle', name: 'topTitle', widget: 'text' }
          - { label: 'content', name: 'content', widget: 'markdown' }
          - { label: 'image', name: 'image', widget: 'image' }
          - { label: 'skill', name: 'skill', widget: 'list', allow_add: true, add_to_top: true, fields: [
              { label: 'title', name: 'title', widget: 'text' },
              { label: 'percent', name: 'percent', widget: 'number', min: 0, max: 100 }] }
      - file: 'data/testimonialSection.yml'
        label: 'Testimonial'
        name: 'testimonial'
        fields:
          - { label: 'enable', name: 'enable', widget: 'boolean' }
          - { label: 'topTitle', name: 'topTitle', widget: 'text' }
          - { label: 'title', name: 'title', widget: 'markdown' }
          - { label: 'testimonial', name: 'testimonial', widget: 'list', allow_add: true, add_to_top: true, fields: [
              {label: 'name', name: 'name', widget: 'string'},
              { label: 'comment', name: 'comment', widget: 'text' },
              { label: 'Date', name: 'time', widget: 'datetime', format: 'MMM DD, YYYY' },
              { label: 'star', name: 'star', widget: 'number', min: 0, max: 5 }] }
      - file: 'data/blogSection.yml'
        label: 'Blog'
        name: 'blog'
        fields:
          - { label: 'enable', name: 'enable', widget: 'boolean' }
          - { label: 'topTitle', name: 'topTitle', widget: 'string' }
          - { label: 'title', name: 'title', widget: 'markdown' }
          - { label: 'buttonText', name: 'buttonText', widget: 'string' }
      - file: 'data/footer.yml'
        label: 'Footer'
        name: 'footer'
        fields:
          - { label: 'background color', name: 'bgColor', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'enable card', name: 'enable1', widget: 'boolean' }
          - { label: 'card background color', name: 'cardBgColor', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'topTitle', name: 'topTitle', widget: 'string' }
          - { label: 'content', name: 'content', widget: 'string' }
          - { label: 'button Text', name: 'btnText', widget: 'string' }
          - { label: 'enable info', name: 'enable2', widget: 'boolean' }
          - { label: 'logo', name: 'footerLogo', widget: 'image' }
          - { label: 'title1', name: 'title1', widget: 'string' }
          - { label: 'content1', name: 'content1', widget: 'list', allow_add: true, add_to_top: true, fields: [
              {label: 'text', name: 'text', widget: 'string'},
              { label: 'url', name: 'url', widget: 'string' }] }
          - { label: 'title2', name: 'title2', widget: 'string' }
          - { label: 'content2', name: 'content2', widget: 'list', hint: 'Icon: https://fontawesome.com/v4.7/icons/', allow_add: true, add_to_top: true, fields: [
              {label: 'icon', name: 'icon', widget: 'string'},
              { label: 'text', name: 'text', widget: 'string' }] }
          - { label: 'copyright', name: 'copyright', widget: 'text' }
          - { label: 'social', name: 'social', widget: 'list', hint: 'Icon: https://fontawesome.com/v4.7/icons/', allow_add: true, add_to_top: true, fields: [
              {label: 'icon', name: 'icon', widget: 'string'},
              { label: 'url', name: 'url', widget: 'string' }] }