# Official Docs: https://www.netlifycms.org/docs/configuration-options/
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# site_url: https://tiiyuu.github.io/test/
display_url: https://tiiyuu.github.io/test/
# logo_url: https://your-site.com/images/logo.svg # for CMS UI logo
publish_mode: editorial_workflow
show_preview_links: true
media_folder: static/images
public_folder: 
  - images
  - images/hero
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    description: 'Create a new post right now!'
    create: true
    extension: 'md'
    slug: '{{year}}_{{month}}_{{day}}_{{hour}}_{{minute}}_{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Feature Image', name: 'featureImage', widget: 'image' }
      - { label: 'Post Image', name: 'postImage', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'data/hero.yml'
        label: 'Hero Page'
        name: 'hero'
        fields:
          - { label: 'Enable', name: 'enable', widget: 'boolean' }
          - { label: 'Title', name: 'title', widget: 'text' }
          - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'ButtonName', name: 'buttonName', widget: 'string' }
          - { label: 'ButtonURL', name: 'buttonURL', widget: 'string' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'VideoThumb', name: 'videoThumb', widget: 'image' }
          - { label: 'VideoURL', name: 'videoURL', widget: 'string' }
      # - file: "site/content/contact/_index.md"
      #   label: "Contact Page"
      #   name: "contact"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Logo, name: logo, widget: image}
      #     - {label: Body, name: body, widget: markdown}
      #     - label: Contact Entries
      #       name: contact_entries
      #       widget: list
      #       fields:
      #         - label: Heading
      #           name: heading
      #           widget: string
      #         - label: Text
      #           name: text
      #           widget: text