# Official Docs: https://www.netlifycms.org/docs/configuration-options/
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# site_url: https://tiiyuu.github.io/test/
display_url: https://tiiyuu.github.io/test/
# logo_url: https://your-site.com/images/logo.svg # for CMS UI logo
publish_mode: editorial_workflow
show_preview_links: true
media_folder: static/images
public_folder: images
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    description: 'Create a new post right now!'
    create: true
    extension: 'md'
    slug: '{{year}}_{{month}}_{{day}}_{{hour}}_{{minute}}_{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', date_format: "MMM DD, YYYY" }
      - { label: 'Feature Image', name: 'featureImage', widget: 'image' }
      - { label: 'Post Image', name: 'postImage', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }